apiVersion: v1
appVersion: 5.7.30
description: mysql 5.7.30
engine: gotpl
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
keywords:
- mysql
- database
- sql
maintainers:
- email: o.with@sportradar.com
  name: olemarkus
- email: viglesias@google.com
  name: viglesiasce
name: mysql5
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/mysql
version: 1.0.0
