---
# Source: rocketmq/charts/rocketmq-namesrv/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-rocketmq-namesrv
  labels:
    helm.sh/chart: rocketmq-namesrv-0.1.0
    app.kubernetes.io/name: rocketmq-namesrv
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "4.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rocketmq-namesrv
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rocketmq-namesrv
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      securityContext:
        {}
      containers:
        - name: rocketmq-namesrv
          securityContext:
            {}
          image: "hub.app-chengdu1.yunzhicloud.com/library/rocketmq-namesrv:4.7.1-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: rocketmq
              containerPort: 9876
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
