---
# Source: rocketmq/charts/rocketmq-namesrv/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-rocketmq-namesrv
  labels:
    helm.sh/chart: rocketmq-namesrv-0.1.0
    app.kubernetes.io/name: rocketmq-namesrv
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "4.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: rocketmq
  selector:
    app.kubernetes.io/name: rocketmq-namesrv
    app.kubernetes.io/instance: RELEASE-NAME
