kind: Secret
apiVersion: v1
metadata:
  name: {{ include "matomo.fullname" . }}-envs
  labels: {{- include "matomo.labels" . | nindent 4 }}
data:
  MATOMO_DATABASE_USERNAME: {{ .Values.database.username | b64enc | quote }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
