FROM node:8-alpine

WORKDIR /app

EXPOSE 8080

#修改时区
ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm install http-server -g

#RUN npm install && npm run build

CMD http-server ./
