FROM node:8-alpine

WORKDIR /app

EXPOSE 8080

#修改时区
ENV TZ=Asia/Shanghai

RUN apk add -U tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

#国内镜像
RUN npm config set registry http://registry.npm.taobao.org/ && \
    npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/

RUN npm install http-server -g

#RUN npm install && npm run build

CMD http-server ./

# docker build -t shoy160/nodejs:8 -f Dockerfile.nodejs .
