FROM jenkins/jenkins:alpine

USER root

# Set locale
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Install node
RUN apk add --update nodejs nodejs-npm \
    && apk add --update sudo \
    && echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# dependencies
RUN npm config set registry https://registry.npm.taobao.org \
    && npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/ \
    && npm i -g yarn cnpm gulp

USER jenkins

# docker build -t shoy160/jenkins:nodejs_alpine -f Dockerfile.jenkins_nodejs_alpine .