apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  namespace: kube-service
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
        - name: master
          image: nacos/nacos-mysql-master:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-master-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "nacos_devtest"
            - name: MYSQL_USER
              value: "nacos"
            - name: MYSQL_PASSWORD
              value: "nacos"
            - name: MYSQL_REPLICATION_USER
              value: "nacos_ru"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "nacos_ru"
      volumes:
        - name: mysql-master-data
          nfs:
            server: 192.168.0.231
            path: /data/nfs/mysql-master
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: kube-service
  labels:
    name: mysql-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-master
