FROM registry.cn-beijing.aliyuncs.com/kubesphereio/builder-nodejs:v3.1.0

RUN npm config set registry https://registry.npm.taobao.org/ \
    && yarn config set registry https://registry.npm.taobao.org/ \
    && npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/ \
    && yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/ \
    && npm -g i n && n latest \
    && npm -g i npm yarn --force