apiVersion: v1
metadata:
  name: pv-mysql01
  namespace: kube-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
  labels:
    pv: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/mysql/node01
    server: 192.168.0.231
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql02
  namespace: kube-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
  labels:
    pv: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/mysql/node02
    server: 192.168.0.231
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql03
  namespace: kube-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
  labels:
    pv: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/mysql/node03
    server: 192.168.0.231
