apiVersion: v1
kind: Service
metadata:
  name: spear
  namespace: kube-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: spear
---

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spear-ingress
  namespace: kube-service
spec:
  rules:
  - host: spear.local
    http:
      paths:
      - path: /
        backend:
          serviceName: spear
          servicePort: 5000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spear
  namespace: kube-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spear
  template:
    metadata:
      labels:
        app: spear
    spec:
      containers:
      - image: docker.dev:5000/spear:1.0.1
        name: spear
        ports:
        - containerPort: 5000
          name: http
