apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq-slave.fullname" . }}
  labels:
    {{- include "rocketmq-slave.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: 10909
      protocol: TCP
      name: tcp-10909
    - port: {{ .Values.service.port2 }}
      targetPort: 10911
      protocol: TCP
      name: tcp-10911
  selector:
    {{- include "rocketmq-slave.selectorLabels" . | nindent 4 }}
