---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.praefect.serviceName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.metricsPort }}"
  {{- end }}
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: {{ include "gitlab.praefect.serviceName" . }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  {{- if .Values.metrics.enabled }}
  - name: praefect-metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
  {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
