# elasticsearch
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-service
spec:
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kube-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:alpine
          name: elasticsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: esdata
              mountPath: '/usr/share/elasticsearch/data'
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: elasticsearch-pvc