apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: kube-service
  labels:
    pv: elasticsearch
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/elk/esdata
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: elasticsearch

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
  namespace: kube-service
  labels:
    pv: logstash
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/elk/logstash
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: logstash
