---
# Source: matomo/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mysql-0.1.0
type: Opaque
data:
  mysql-root-password: "bmlEY09PRmVUNQ=="
  mysql-password: "bWF0b21v"
