apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.fullname" . }}-cm
data:
  {{- with .Values.mysql }}
  mysql.host: {{ .host }}
  mysql.port: {{ .port | quote }}
  mysql.database: {{ .database }}  
  mysql.user: {{ .user }}
  mysql.password: {{ .password }}
  {{- end }}