apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.rpcPort }}
      name: rpc
      targetPort: 7848
      protocol: TCP
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
