# Default values for rocketmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
brokerCount: 1

image:
  namesrv:
    repository: rocketmqinc/rocketmq-namesrv
    pullPolicy: IfNotPresent
    tag: "4.5.0-alpine"
  broker:
    repository: rocketmqinc/rocketmq-broker
    pullPolicy: IfNotPresent
    tag: "4.5.0-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

broker:
  nameOverride: ""
  fullnameOverride: ""

persistence:
  size: 2Gi

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9876

resources: 
  namesrv:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi
  broker:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

tests:
  enabled: false
