apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-oap
  namespace: skywalking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skywalking-oap
  namespace: skywalking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skywalking-oap
subjects:
  - kind: ServiceAccount
    name: skywalking-oap
    namespace: skywalking

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: skywalking
  name: skywalking-oap
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: Service
metadata:
  name: oap
  namespace: skywalking
  labels:
    service: oap
spec:
  ports:
    - port: 12800
      name: rest
    - port: 11800
      name: grpc
    - port: 1234
      name: page
  selector:
    app: oap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oap
  namespace: skywalking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oap
  template:
    metadata:
      labels:
        app: oap
        release: skywalking
    spec:
      serviceAccountName: skywalking-oap
      containers:
        - name: oap
          image: apache/skywalking-oap-server:6.6.0-es6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11800
              name: grpc
            - containerPort: 12800
              name: rest
          env:
            - name: JAVA_OPTS
              value: -Xms256M -Xmx512M
            - name: SW_STORAGE
              value: elasticsearch
            - name: SW_STORAGE_ES_CLUSTER_NODES
              value: elasticsearch.kube-service:9200
            # - name: SW_STORAGE_ES_CLUSTER_NODES
            #   value: "192.168.78.136:9200"
            # - name: SW_CLUSTER
            #   value: kubernetes
            # - name: SW_CLUSTER_K8S_NAMESPACE
            #   value: skywalking
            # - name: SW_SERVICE_MESH_OFFSET_MAX_FILE_SIZE
            #   value: "200"
            # - name: SW_RECEIVER_BUFFER_DATA_MAX_FILE_SIZE
            #   value: "800"
            # - name: SW_RECEIVER_BUFFER_FILE_CLEAN_WHEN_RESTART
            #   value: "true"
