apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: 10909
      protocol: TCP
      name: tcp-10909
    - port: {{ .Values.service.port2 }}
      targetPort: 10911
      protocol: TCP
      name: tcp-10911
    - port: {{ .Values.service.port3 }}
      targetPort: 10912
      protocol: TCP
      name: tcp-10912
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
