apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.fullname" . }}-cm
data:
  {{- with .Values.global.mysql }}
  mysql.db.name: {{ .database }}
  mysql.port: "3306"
  mysql.user: {{ .user }}
  mysql.password: {{ .password }}
  {{- end }}