---
# Source: matomo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: matomo-1.0.1
    app.kubernetes.io/component: app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/component: app
      annotations:
        checksum/config: 9822eff58756b05d14355c96df4eb542391ef0fa47d7cb0a2d447be1f7f40a9
        checksum/secret: 079c46a1dd57972b482f62db07463bc9876ed5042970ea80d5461b680ce87a3
    spec:
      containers:
        - name: matomo
          image: "t3nde/matomo:4.0.3-fpm-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: MATOMO_GENERAL_ENABLE_TRUSTED_HOST_CHECK
              value: "0"
            - name: MATOMO_DATABASE_HOST
              value: "RELEASE-NAME-mysql"
            - name: MATOMO_DATABASE_ADAPTER
              value: "PDO\\MYSQL"
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: "matomo_"
            - name: MATOMO_DATABASE_DBNAME
              value: "matomo"
            - name: MATOMO_GENERAL_SALT
              value: "matomo168"
          envFrom:
            - secretRef:
                name: RELEASE-NAME-matomo-envs
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: 
            - name: html-files
              mountPath: /var/www/html
        - name: nginx
          image: "nginx:1.18.0-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /matomo.php
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /matomo.php
              port: http
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 25
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: matomo.conf
            - name: html-files
              mountPath: /var/www/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: RELEASE-NAME-matomo
        - name: config
          configMap:
            name: RELEASE-NAME-matomo
        - name: html-files
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: matomo
                    app.kubernetes.io/instance: RELEASE-NAME
                    app.kubernetes.io/component: app
