---
# Source: matomo/templates/secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: RELEASE-NAME-matomo-envs
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: matomo-1.0.1
data:
  MATOMO_DATABASE_USERNAME: "bWF0b21v"
  MATOMO_DATABASE_PASSWORD: "bWF0b21v"
