apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-nexus-pv
  namespace: kube-service
  labels:
    pv: repo-nexus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/repo-nexus
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-nexus-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: repo-nexus
