apiVersion: v1
kind: Service
metadata:
  name: repo-nexus
  namespace: kube-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 8081
    name: web-ui
  - port: 5000
    targetPort: 5000
    nodePort: 5100
    name: docker-group
  - port: 8889
    targetPort: 8889
    nodePort: 5101
    name: docker-push
  selector:
    app: repo-nexus

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo-nexus
  namespace: kube-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: repo-nexus
  template:
    metadata:
      labels:
        app: repo-nexus
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: IfNotPresent
        name: repo-nexus
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
        - name: repo-nexus-storge
          mountPath: /nexus-data
      volumes:
      - name: repo-nexus-storge
        persistentVolumeClaim:
          claimName: repo-nexus-pvc
