apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-nuget-package-pv
  namespace: kube-service
  labels:
    pv: repo-nuget-package
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/nuget/packages
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-nuget-package-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: repo-nuget-package

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-nuget-db-pv
  namespace: kube-service
  labels:
    pv: repo-nuget-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/nuget/data
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-nuget-db-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: repo-nuget-db
