---
# Source: superset/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-superset
  labels:
    app: superset
    chart: superset-1.2.0
    release: RELEASE-NAME
    heritage: Helm
type: Opaque
data:
  init_superset.sh: "L3Vzci9sb2NhbC9iaW4vc3VwZXJzZXQtaW5pdCAtLXVzZXJuYW1lIGFkbWluIC0tZmlyc3RuYW1lIGFkbWluIC0tbGFzdG5hbWUgdXNlciAtLWVtYWlsIGFkbWluQGZhYi5vcmcgLS1wYXNzd29yZCBhZG1pbgpzdXBlcnNldCBydW4="
  superset_config.py: "Iy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIFN1cGVyc2V0IHNwZWNpZmljIGNvbmZpZwojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tClJPV19MSU1JVCA9IDUwMDAKU1VQRVJTRVRfV09SS0VSUyA9IDIKClNVUEVSU0VUX1dFQlNFUlZFUl9QT1JUID0gODA4OAojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiMgRmxhc2sgQXBwIEJ1aWxkZXIgY29uZmlndXJhdGlvbgojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiMgWW91ciBBcHAgc2VjcmV0IGtleQpTRUNSRVRfS0VZID0gJ1wyXDF0aGlzaXNteXNjcmV0a2V5XDFcMlxlXHlceVxoJwoKIyBUaGUgU1FMQWxjaGVteSBjb25uZWN0aW9uIHN0cmluZyB0byB5b3VyIGRhdGFiYXNlIGJhY2tlbmQKIyBUaGlzIGNvbm5lY3Rpb24gZGVmaW5lcyB0aGUgcGF0aCB0byB0aGUgZGF0YWJhc2UgdGhhdCBzdG9yZXMgeW91cgojIHN1cGVyc2V0IG1ldGFkYXRhIChzbGljZXMsIGNvbm5lY3Rpb25zLCB0YWJsZXMsIGRhc2hib2FyZHMsIC4uLikuCiMgTm90ZSB0aGF0IHRoZSBjb25uZWN0aW9uIGluZm9ybWF0aW9uIHRvIGNvbm5lY3QgdG8gdGhlIGRhdGFzb3VyY2VzCiMgeW91IHdhbnQgdG8gZXhwbG9yZSBhcmUgbWFuYWdlZCBkaXJlY3RseSBpbiB0aGUgd2ViIFVJClNRTEFMQ0hFTVlfREFUQUJBU0VfVVJJID0gJ3NxbGl0ZTovLy8vdmFyL2xpYi9zdXBlcnNldC9zdXBlcnNldC5kYicKCgojIEZsYXNrLVdURiBmbGFnIGZvciBDU1JGCldURl9DU1JGX0VOQUJMRUQgPSBUcnVlCiMgQWRkIGVuZHBvaW50cyB0aGF0IG5lZWQgdG8gYmUgZXhlbXB0IGZyb20gQ1NSRiBwcm90ZWN0aW9uCldURl9DU1JGX0VYRU1QVF9MSVNUID0gW10KCiMgU2V0IHRoaXMgQVBJIGtleSB0byBlbmFibGUgTWFwYm94IHZpc3VhbGl6YXRpb25zCk1BUEJPWF9BUElfS0VZID0gJyc="
