---
# Source: superset/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-superset
  labels:
    app: superset
    chart: superset-1.2.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 8088
      protocol: TCP
  selector:
    app: superset
    release: RELEASE-NAME
    component: server
