apiVersion: v1
kind: PersistentVolume
metadata:
  name: dns-pv
  namespace: kube-service
  labels:
    pv: dns
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/dns
    server: 192.168.0.231

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-pvc
  namespace: kube-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: dns
