apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: kube-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: 53
  selector:
    app: dns
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dns-ingress
  namespace: kube-service
spec:
  rules:
  - host: dns.local
    http:
      paths:
      - path: /
        backend:
          serviceName: dns
          servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dns
  namespace: kube-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      containers:
      - image: jpillora/dnsmasq
        name: dns
        #args: ["-log-opt","max-size=100m"]
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 53
          protocol: UDP
          name: udp
        env:
        - name: HTTP_USER
          value: admin
        - name: HTTP_PASS
          value: "icb@168"
        volumeMounts:
        - name: dns-storge
          mountPath: /etc/dnsmasq.conf
          subPath: dnsmasq.conf
      volumes:
      - name: dns-storge
        persistentVolumeClaim:
          claimName: dns-pvc
