apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10909
      targetPort: 10909
      protocol: TCP
      name: tcp-10909
    - port: 10911
      targetPort: 10911
      protocol: TCP
      name: tcp-10911
    - port: 10912
      targetPort: 10912
      protocol: TCP
      name: tcp-10912
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
