---
# Source: zookeeper/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-zookeeper-headless
  labels:
    helm.sh/chart: zookeeper-1.0.0
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "3.6.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: election
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: RELEASE-NAME
