apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 5000
  - name: http-ui
    port: 8080
    targetPort: 8080
    nodePort: 5001
  selector:
    app: docker-registry

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - image: registry:2
        name: docker-registry
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: docker-registry-storge
          mountPath: /var/lib/registry
      - image: atcol/docker-registry-ui
        name: docker-registry-ui
        env:
        - name: REG1
          value: http://192.168.0.231:5000/v2/
        ports:
        - containerPort: 8080
          name: http-ui
      volumes:
      - name: docker-registry-storge
        persistentVolumeClaim:
          claimName: docker-registry-pvc
