apiVersion: v1
kind: Service
metadata:
  labels:
    app: hainan-oa-biz
    app.kubernetes.io/name: hainan-biz
    app.kubernetes.io/version: v1
  name: hainan-oa-biz
  namespace: hainan-test
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hainan-oa-biz
    app.kubernetes.io/name: hainan-biz
    app.kubernetes.io/version: v1
  sessionAffinity: None
  type: ClusterIP
